export const FontSizes = {
    number: 20,
    button: 20,
    text: 24,
    buttonText: 24,
    advancedButtonText: 20,
    textInputWrite: 20,
    textInput: 22,
    textResult: 18,
    commandDictName: 18,
    commandDictCommand: 24,
    constantDictName: 18,
    constantDictValue: 24,
    simpleCalculatorInput: 28,
    simpleCalculatorResult: 22,
    aboutBody: 14,
    aboutTitles: 20,
    settingsHeader: 18,
    settingItem: 24,
}
